<?php

namespace Btn\FaqBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqCategoryRepository extends EntityRepository
{
    public function getSearchQuery($conditions)
    {
        $qb = $this->createQueryBuilder('fc')
            ->select('fc')
        ;
        if (!empty($conditions) && is_array($conditions)) {
            $expr = call_user_func_array(array($qb->expr(), 'andx'), $conditions);
            $qb->where($expr);
        }

        return $qb;
    }

    /**
     * @return \Btn\FaqBundle\FaqCategory[]
     */
    public function findAllVisible()
    {
        $query = $this
            ->createQueryBuilder('fc')
            ->andWhere('fc.visible = :visible')
            ->orderBy('fc.position', 'ASC')
            ->setParameter(':visible', 1)
            ->getQuery()
        ;

        return $query->getResult();
    }
}
